In [ ]:
import pandas as pd
from google.colab import files
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
uploaded = files.upload()
df = pd.read_csv("sample_submition.csv")

Saving sample_submition.csv to sample_submition (1).csv

In [ ]:
df

     index Onshore/Offshore
0        0          ONSHORE
1        1         OFFSHORE
2        2          ONSHORE
3        3         OFFSHORE
4        4          ONSHORE
..     ...              ...
273    273          ONSHORE
274    274         OFFSHORE
275    275          ONSHORE
276    276          ONSHORE
277    277          ONSHORE

[278 rows x 2 columns]

In [ ]:
uploaded = files.upload()
test = pd.read_csv("test_final.csv")
test

Saving test_final.csv to test_final (2).csv

,Tectonic regime,Hydrocarbon type,Reservoir status,Structural setting,Depth,Period,Lithology,Gross,Netpay,Porosity,Permeability
0,COMPRESSION/EVAPORITE/EXTENSION/GRAVITY/INVERSION,GAS,DECLINING PRODUCTION,INVERSION/SUB-SALT,7420.000000,PERMIAN,SANDSTONE,715.000000,580.000000,11.000000,0.500000
1,EXTENSION,OIL,NEARLY DEPLETED,PASSIVE,4843.000000,PALEOGENE,SANDSTONE,2133.000000,72.000000,23.000000,350.000000
2,COMPRESSION/EXTENSION/INVERSION,OIL,DEVELOPING,INVERSION/RIFT,8450.000000,CRETACEOUS,LOW-RESISTIVITY SANDSTONE,145.000000,45.000000,18.000000,700.000000
3,COMPRESSION/EROSION,OIL,MATURE PRODUCTION,FORELAND,5463.000000,DEVONIAN,SANDSTONE,115.000000,29.000000,19.000000,375.000000
4,BASEMENT-I/STRIKE-SLIP/TRANSPRESSION,OIL,DEVELOPING,INVERSION/WRENCH,3520.000000,NEOGENE,SANDSTONE,2460.000000,220.000000,20.000000,45.000000
...,...,...,...,...,...,...,...,...,...,...,...
273,BASEMENT-I/COMPRESSION/EROSION/STRIKE-SLIP/TRA...,OIL,NEARLY DEPLETED,FORELAND/WRENCH,1683.811578,NEOGENE,THINLY-BEDDED SANDSTONE,639.294026,147.858805,34.129412,2157.646429
274,COMPRESSION/EROSION/EXTENSION/INVERSION,OIL,NEARLY DEPLETED,FORELAND/INVERSION/RIFT,5877.960131,CRETACEOUS,DOLOMITE,973.664850,178.946119,13.947543,47.896985
275,BASEMENT-I/COMPRESSION/EROSION/STRIKE-SLIP/TRA...,OIL,NEARLY DEPLETED,FORELAND/WRENCH,1695.923184,NEOGENE,THINLY-BEDDED SANDSTONE,645.238373,149.047675,34.092260,2198.513813
276,BASEMENT-I/COMPRESSION/EROSION/STRIKE-SLIP/TRA...,OIL,MATURE PRODUCTION,FORELAND/WRENCH,1429.162420,NEOGENE,SANDSTONE,514.312844,122.862569,34.910545,1298.400805
277,COMPRESSION/EROSION/EXTENSION/INVERSION,OIL,NEARLY DEPLETED,FORELAND/INVERSION/RIFT,6417.577091,CRETACEOUS,DOLOMITE,1235.696896,195.851413,11.580802,17.467457

In [ ]:
uploaded = files.upload()
train = pd.read_csv("train_final.csv")
train

Saving train_final.csv to train_final (2).csv

,Tectonic regime,Onshore/Offshore,Hydrocarbon type,Reservoir status,Structural setting,Depth,Period,Lithology,Gross,Netpay,Porosity,Permeability
0,COMPRESSION,ONSHORE,OIL,MATURE PRODUCTION,FORELAND,15250.000000,PALEOGENE,SANDSTONE,8000.000000,575.000000,5.000000,0.100000
1,COMPRESSION/EVAPORITE/EXTENSION/INVERSION,OFFSHORE,GAS-CONDENSATE,PLATEAU PRODUCTION,RIFT/SALT,16360.000000,JURASSIC,SANDSTONE,980.000000,490.000000,16.000000,10.000000
2,COMPRESSION/EROSION,ONSHORE,OIL,DECLINING PRODUCTION,FORELAND,4700.000000,PERMIAN,DOLOMITE,65.000000,21.000000,8.000000,0.500000
3,COMPRESSION/EVAPORITE/EXTENSION/GRAVITY/INVERSION,OFFSHORE,OIL,DEVELOPING,FORELAND/RIFT/SALT,8105.345849,CRETACEOUS,SANDSTONE,116.037254,41.595776,14.984042,29.920211
4,COMPRESSION/EROSION,ONSHORE,OIL,NEARLY DEPLETED,FORELAND,7600.000000,CRETACEOUS,SANDSTONE,158.000000,15.000000,9.500000,10.000000
...,...,...,...,...,...,...,...,...,...,...,...,...
350,COMPRESSION/EROSION,ONSHORE-OFFSHORE,OIL,MATURE PRODUCTION,WRENCH/FORELAND,1400.000000,NEOGENE,SANDSTONE,500.000000,120.000000,35.000000,1200.000000
351,COMPRESSION/EROSION,ONSHORE-OFFSHORE,OIL,NEARLY DEPLETED,FORELAND,6550.000000,CRETACEOUS,DOLOMITE,1300.000000,200.000000,11.000000,10.000000
352,STRIKE-SLIP/TRANSPRESSION/BASEMENT-I,ONSHORE-OFFSHORE,OIL,NEARLY DEPLETED,WRENCH,2326.000000,NEOGENE,THINLY-BEDDED SANDSTONE,700.000000,375.000000,28.000000,400.000000
353,STRIKE-SLIP/TRANSPRESSION/BASEMENT-I,ONSHORE-OFFSHORE,OIL,NEARLY DEPLETED,WRENCH,1726.000000,NEOGENE,THINLY-BEDDED SANDSTONE,660.000000,152.000000,34.000000,2300.000000
354,INVERSION/COMPRESSION/EXTENSION,ONSHORE-OFFSHORE,OIL,DECLINING PRODUCTION,RIFT/INVERSION,4954.000000,TRIASSIC,SANDSTONE,525.000000,150.000000,18.000000,100.000000

In [ ]:
train = pd.read_csv("train_final.csv")
test = pd.read_csv("test_final.csv")

In [ ]:
print(train.shape)
print(test.shape)
print('_'*30)
print(train.info())
print(test.dtypes)
print('_'*30)
print(train.isna().sum())
print('_'*30)
print(test.isna().sum())

(355, 12)
(278, 11)
______________________________
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 355 entries, 0 to 354
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Tectonic regime     355 non-null    object
 1   Onshore/Offshore    355 non-null    object
 2   Hydrocarbon type    355 non-null    object
 3   Reservoir status    355 non-null    object
 4   Structural setting  355 non-null    object
 5   Depth               355 non-null    float64
 6   Period              355 non-null    object
 7   Lithology           355 non-null    object
 8   Gross               355 non-null    float64
 9   Netpay              355 non-null    float64
 10  Porosity            355 non-null    float64
 11  Permeability        355 non-null    float64
dtypes: float64(5), object(7)
memory usage: 33.4+ KB
None
Tectonic regime        object
Hydrocarbon type       object
Reservoir status       object
Structural setting     object
Depth                 float64
Period                 object
Lithology              object
Gross                 float64
Netpay                float64
Porosity              float64
Permeability          float64
dtype: object
______________________________
Tectonic regime       0
Onshore/Offshore      0
Hydrocarbon type      0
Reservoir status      0
Structural setting    0
Depth                 0
Period                0
Lithology             0
Gross                 0
Netpay                0
Porosity              0
Permeability          0
dtype: int64
______________________________
Tectonic regime       0
Hydrocarbon type      0
Reservoir status      0
Structural setting    0
Depth                 0
Period                0
Lithology             0
Gross                 0
Netpay                0
Porosity              0
Permeability          0
dtype: int64

In [ ]:
#смотрим какие категориальные признаки есть в датасете

print(train['Tectonic regime'].unique())
print('_'*30)
print(train['Onshore/Offshore'].unique())
print('_'*30)
print(train['Hydrocarbon type'].unique())
print('_'*30)
print(train['Reservoir status'].unique())
print('_'*30)
print(train['Structural setting'].unique())
print('_'*30)
print(train['Period'].unique())
print('_'*30)
print(train['Lithology'].unique())
print('_'*30)

['COMPRESSION' 'COMPRESSION/EVAPORITE/EXTENSION/INVERSION'
 'COMPRESSION/EROSION' 'COMPRESSION/EVAPORITE/EXTENSION/GRAVITY/INVERSION'
 'EXTENSION' 'COMPRESSION/EXTENSION/INVERSION'
 'EVAPORITE/EXTENSION/GRAVITY'
 'COMPRESSION/EROSION/EXTENSION/INVERSION/SHALE' 'COMPRESSION/EVAPORITE'
 'BASEMENT-I/EVAPORITE/EXTENSION/GRAVITY/INVERSION/STRIKE-SLIP/SYNSEDIMENTATION/TRANSPRESSION'
 'EXTENSION/INVERSION'
 'BASEMENT-I/EXTENSION/INVERSION/STRIKE-SLIP/TRANSPRESSION'
 'COMPRESSION/EVAPORITE/EXTENSION/GRAVITY/LINKED'
 'COMPRESSION/EROSION/EVAPORITE/EXTENSION/GRAVITY/INVERSION'
 'COMPRESSION/EROSION/EXTENSION/INVERSION'
 'COMPRESSION/EROSION/EVAPORITE/EXTENSION/INVERSION'
 'DIAPIR/EVAPORITE/EXTENSION/GRAVITY/SYNSEDIMENTATION'
 'BASEMENT-I/COMPRESSION/EXTENSION/INVERSION/SHALE/STRIKE-SLIP/TRANSPRESSION'
 'COMPRESSION/EXTENSION/GRAVITY/SHALE/SYNSEDIMENTATION'
 'COMPRESSION/EVAPORITE/GRAVITY' 'EROSION/EXTENSION' 'COMPRESSION/SHALE'
 'EXTENSION/LINKED/SHALE/TRANSTENSION'
 'COMPRESSION/EVAPORITE/EXTENSION/GRAVITY/LINKED/SHALE/SYNSEDIMENTATION'
 'EROSION/EVAPORITE/EXTENSION/INVERSION'
 'EVAPORITE/EXTENSION/GRAVITY/SYNSEDIMENTATION'
 'COMPRESSION/EXTENSION/LINKED' 'EXTENSION/GRAVITY/SHALE/SYNSEDIMENTATION'
 'COMPRESSION/EVAPORITE/EXTENSION/GRAVITY'
 'DIAPIR/EROSION/EVAPORITE/EXTENSION/GRAVITY/SYNSEDIMENTATION'
 'COMPRESSION/EVAPORITE/EXTENSION/LINKED'
 'BASEMENT-I/COMPRESSION/EXTENSION/INVERSION/STRIKE-SLIP/TRANSPRESSION'
 'BASEMENT-I/EXTENSION/GRAVITY/SHALE/STRIKE-SLIP/SYNSEDIMENTATION/TRANSPRESSION'
 'EROSION/EVAPORITE/EXTENSION/GRAVITY'
 'COMPRESSION/EXTENSION/GRAVITY/LINKED/SHALE'
 'COMPRESSION/EXTENSION/GRAVITY/INVERSION/SHALE/SYNSEDIMENTATION'
 'STRIKE-SLIP/TRANSPRESSION' 'TRANSPRESSION/UPLIFT'
 'COMPRESSION/EVAPORITE/EXTENSION/GRAVITY/INVERSION/LINKED/SHALE'
 'COMPRESSION/EVAPORITE/EXTENSION' 'EROSION/EVAPORITE/EXTENSION'
 'BASEMENT-I/COMPRESSION/STRIKE-SLIP/TRANSPRESSION'
 'BASEMENT-I/EVAPORITE/SHALE/STRIKE-SLIP/TRANSTENSION'
 'COMPRESSION/EVAPORITE/EXTENSION/GRAVITY/INVERSION/SYNSEDIMENTATION'
 'BASEMENT-I/EVAPORITE/EXTENSION/GRAVITY/SHALE/STRIKE-SLIP/TRANSTENSION'
 'EVAPORITE/EXTENSION'
 'COMPRESSION/EROSION/EXTENSION/GRAVITY/INVERSION/SHALE'
 'BASEMENT-I/STRIKE-SLIP/TRANSPRESSION' 'EROSION/EXTENSION/GRAVITY/SHALE'
 'COMPRESSION/EXTENSION/INVERSION/SHALE' 'BASEMENT-I/STRIKE-SLIP'
 'EXTENSION/GRAVITY/SHALE' 'COMPRESSION/EROSION/EXTENSION'
 'EVAPORITE/EXTENSION/INVERSION'
 'COMPRESSION/EROSION/EVAPORITE/EXTENSION/GRAVITY'
 'BASEMENT-I/COMPRESSION/REACTIVATION/SHALE'
 'DIAPIR/EVAPORITE/EXTENSION/GRAVITY' 'BASEMENT-I/COMPRESSION/STRIKE-SLIP'
 'COMPRESSION/EXTENSION' 'COMPRESSION/EROSION/EXTENSION/LINKED'
 'COMPRESSION/DIAPIR/EVAPORITE/EXTENSION/GRAVITY/INVERSION/SYNSEDIMENTATION'
 'COMPRESSION/EXTENSION/INVERSION/STRIKE-SLIP'
 'BASEMENT-I/COMPRESSION/EVAPORITE/GRAVITY/STRIKE-SLIP'
 'COMPRESSION/EROSION/EVAPORITE/EXTENSION'
 'EROSION/EXTENSION/GRAVITY/SHALE/SYNSEDIMENTATION'
 'STRIKE-SLIP/TRANSPRESSION/BASEMENT-I' 'INVERSION/COMPRESSION/EXTENSION']
______________________________
['ONSHORE' 'OFFSHORE' 'ONSHORE-OFFSHORE']
______________________________
['OIL' 'GAS-CONDENSATE' 'GAS' 'CARBON DIOXIDE' 'METHANE HYDRATE']
______________________________
['MATURE PRODUCTION' 'PLATEAU PRODUCTION' 'DECLINING PRODUCTION'
 'DEVELOPING' 'NEARLY DEPLETED' 'CONTINUING DEVELOPMENT' 'UNKNOWN'
 'SECOND PLATEAU PRODUTION' 'UNDEVELOPED' 'REJUVENATING' 'ABANDONED'
 'DEPLETED']
______________________________
['FORELAND' 'RIFT/SALT' 'FORELAND/RIFT/SALT' 'THRUST' 'RIFT'
 'INVERSION/RIFT' 'PASSIVE' 'PASSIVE/RIFT' 'BACKARC/RIFT'
 'BACKARC/INVERSION/PASSIVE' 'INVERSION/RIFT/SALT' 'INTRACRATONIC'
 'BACKARC/INVERSION' 'FORELAND/SALT' 'INVERSION/RIFT/SUB-SALT'
 'PASSIVE/RIFT/SUB-SALT' 'DELTA/PASSIVE/SALT'
 'INVERSION/RIFT/THRUST/WRENCH' 'BACKARC/DELTA/FORELAND'
 'FORELAND/SUB-THRUST/THRUST' 'RIFT/WRENCH' 'INVERSION/PASSIVE/RIFT/SALT'
 'DELTA/FORELAND/THRUST' 'FORELAND/THRUST' 'RIFT/SUB-SALT' 'PASSIVE/SALT'
 'DELTA/FORELAND' 'DELTA/PASSIVE/RIFT/SALT' 'FORELAND/PASSIVE'
 'BACKARC/INVERSION/WRENCH' 'PASSIVE/RIFT/SALT' 'DELTA/INVERSION/WRENCH'
 'PASSIVE/SUB-SALT' 'SUB-THRUST' 'DELTA/PASSIVE/SUB-SALT'
 'FORELAND/SUB-SALT' 'DELTA/PASSIVE' 'BACKARC/DELTA/FORELAND/INVERSION'
 'INVERSION/SUB-SALT' 'FOREARC/INVERSION/RIFT' 'BACKARC/INVERSION/RIFT'
 'INTRACRATONIC/SUB-SALT' 'THRUST/WRENCH' 'DELTA/WRENCH'
 'DELTA/RIFT/SALT/WRENCH' 'DELTA/INVERSION/PASSIVE/RIFT'
 'FORELAND/INVERSION' 'FOREARC/INVERSION' 'FORELAND/SUB-THRUST'
 'DELTA/PASSIVE/RIFT' 'FORELAND/WRENCH' 'FORELAND/INVERSION/SUB-SALT'
 'BACKARC' 'FORELAND/INVERSION/RIFT/SALT' 'INVERSION/PASSIVE/RIFT'
 'WRENCH' 'FORELAND/INVERSION/SALT/SUB-SALT' 'FORELAND/INVERSION/SALT'
 'DELTA/FORELAND/INVERSION/RIFT' 'FORELAND/SALT/WRENCH' 'SUB-SALT'
 'DELTA/RIFT/WRENCH' 'INVERSION/WRENCH' 'WRENCH/FORELAND' 'RIFT/INVERSION']
______________________________
['PALEOGENE' 'JURASSIC' 'PERMIAN' 'CRETACEOUS' 'NEOGENE' 'CARBONIFEROUS'
 'ORDOVICIAN' 'DEVONIAN' 'CRETACEOUS-PALEOGENE' 'CARBONIFEROUS-CRETACEOUS'
 'JURASSIC-CRETACEOUS' 'PROTEROZOIC' 'PALEOZOIC' 'PALEOGENE-NEOGENE'
 'ARCHEAN' 'TRIASSIC' 'CARBONIFEROUS-PERMIAN' 'TRIASSIC-JURASSIC'
 'CAMBRIAN-ORDOVICIAN' 'PROTEROZOIC-CAMBRIAN' 'CAMBRIAN']
______________________________
['SANDSTONE' 'DOLOMITE' 'CONGLOMERATE' 'CHALKY LIMESTONE' 'CHALK'
 'LIMESTONE' 'SILTSTONE' 'THINLY-BEDDED SANDSTONE' 'BASEMENT'
 'LOW-RESISTIVITY SANDSTONE' 'SHALE' 'DOLOMITIC LIMESTONE' 'CHERT'
 'DIATOMITE']
______________________________

In [ ]:
d={'ONSHORE' : 0, 'OFFSHORE': 1, 'ONSHORE-OFFSHORE': 2}
train['Onshore/Offshore']=train['Onshore/Offshore'].map(d)

In [ ]:
# Выделим категориальные признаки, преобразуем их.



label_encoder = preprocessing.LabelEncoder() 
label_encoder.fit(train['Tectonic regime']) 
train['Tectonic regime'] = label_encoder.transform(train['Tectonic regime'])


label_encoder = preprocessing.LabelEncoder() 
label_encoder.fit(train['Hydrocarbon type']) 
train['Hydrocarbon type'] = label_encoder.transform(train['Hydrocarbon type'])

label_encoder = preprocessing.LabelEncoder() 
label_encoder.fit(train['Reservoir status']) 
train['Reservoir status'] = label_encoder.transform(train['Reservoir status'])


label_encoder = preprocessing.LabelEncoder() 
label_encoder.fit(train['Structural setting']) 
train['Structural setting'] = label_encoder.transform(train['Structural setting'])


label_encoder = preprocessing.LabelEncoder() 
label_encoder.fit(train['Period']) 
train['Period'] = label_encoder.transform(train['Period'])


label_encoder = preprocessing.LabelEncoder() 
label_encoder.fit(train['Lithology']) 
train['Lithology'] = label_encoder.transform(train['Lithology'])


train=train.drop(['Tectonic regime'], axis=1)

train.head()

,Onshore/Offshore,Hydrocarbon type,Reservoir status,Structural setting,Depth,Period,Lithology,Gross,Netpay,Porosity,Permeability
0,0,4,5,23,15250.000000,13,10,8000.000000,575.000000,5.000000,0.100000
1,1,2,7,56,16360.000000,9,10,980.000000,490.000000,16.000000,10.000000
2,0,4,2,23,4700.000000,16,6,65.000000,21.000000,8.000000,0.500000
3,1,4,4,30,8105.345849,6,10,116.037254,41.595776,14.984042,29.920211
4,0,4,6,23,7600.000000,6,10,158.000000,15.000000,9.500000,10.000000

In [ ]:
# Выделим категориальные признаки, преобразуем их.



label_encoder = preprocessing.LabelEncoder() 
label_encoder.fit(test['Tectonic regime']) 
test['Tectonic regime'] = label_encoder.transform(test['Tectonic regime'])

label_encoder = preprocessing.LabelEncoder() 
label_encoder.fit(test['Hydrocarbon type']) 
test['Hydrocarbon type'] = label_encoder.transform(test['Hydrocarbon type'])

label_encoder = preprocessing.LabelEncoder() 
label_encoder.fit(test['Reservoir status']) 
test['Reservoir status'] = label_encoder.transform(test['Reservoir status'])


label_encoder = preprocessing.LabelEncoder() 
label_encoder.fit(test['Structural setting']) 
test['Structural setting'] = label_encoder.transform(test['Structural setting'])


label_encoder = preprocessing.LabelEncoder() 
label_encoder.fit(test['Period']) 
test['Period'] = label_encoder.transform(test['Period'])


label_encoder = preprocessing.LabelEncoder() 
label_encoder.fit(test['Lithology']) 
test['Lithology'] = label_encoder.transform(test['Lithology'])


test.head()

,Tectonic regime,Hydrocarbon type,Reservoir status,Structural setting,Depth,Period,Lithology,Gross,Netpay,Porosity,Permeability
0,15,0,2,22,7420.0,11,6,715.0,580.0,11.0,0.5
1,29,2,5,24,4843.0,10,6,2133.0,72.0,23.0,350.0
2,20,2,3,19,8450.0,3,5,145.0,45.0,18.0,700.0
3,9,2,4,9,5463.0,5,6,115.0,29.0,19.0,375.0
4,6,2,3,23,3520.0,9,6,2460.0,220.0,20.0,45.0

In [ ]:
from sklearn.model_selection import train_test_split
X = train.drop(['Onshore/Offshore'], axis=1)
y = train['Onshore/Offshore']

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=42)

In [ ]:
scaler = StandardScaler()
X_st = scaler.fit_transform(X)
# fit()
# transform()

X_train_m, X_test_m, y_train_m, y_test_m = train_test_split(X,y, test_size=0.3, random_state=42)

In [ ]:
# Логистическая регрессия без масштабирования




log = LogisticRegression()

# модель учится, для этого ей нужны ответы
log.fit(X_train, y_train)

# тестируем, для признаков у которых нет ответов, мы предсказывает ответ
answers_pred = log.predict(X_test)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

In [ ]:
# Как оценить насколько хорошо работает ваша модель?

# answers_pred - ответы которые вернула модель для X_test
# y_test - это правильные ответы для X_test
print(accuracy_score(y_test,answers_pred))

#модель дает правильные ответы для 64% выборки

0.6448598130841121

In [ ]:
# Уравнение регрессии:
print('y = ')
[print(coef, end = "x + ") for coef in log.coef_[0]]
print(log.intercept_[0])

y =
0.001744045106526495x + 0.003180213404052677x + 0.010514917535764653x + 0.00017693154856434216x + 0.002042768801830136x + 0.00225325510277163x + 0.0002552172518302478x + -0.0008619059181774002x + -0.002047543615013635x + -0.00015345763169110274x + 0.0005314670005317497

In [ ]:
#логистическая регрессия с масштабированием


log = LogisticRegression()

# модель учится, для этого ей нужны ответы
log.fit(X_train_m, y_train_m)

# тестируем, для признаков у которых нет ответов, мы предсказывает ответ
answers_pred = log.predict(X_test_m)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

In [ ]:
print(accuracy_score(y_test_m,answers_pred))

0.6448598130841121

In [ ]:
# Mетод ближайших соседей без маштабирования

from sklearn.neighbors import KNeighborsClassifier


# создаем модель
# как подобрать лучшее число соседей?
scores = []
for i in range(1,20):

    knn = KNeighborsClassifier(i)
    # log = LogisticRegression()
    knn.fit(X_train,y_train)
    answers = knn.predict(X_test) # метод predict возвращыет вектор ответов для X_test
    
    scores.append(knn.score(X_test,y_test))
    # accuracy_score(y_test,answers)

print(scores)

[0.7476635514018691, 0.8130841121495327, 0.7570093457943925, 0.7850467289719626, 0.7476635514018691, 0.719626168224299, 0.7009345794392523, 0.7009345794392523, 0.7009345794392523, 0.7009345794392523, 0.6728971962616822, 0.6635514018691588, 0.6915887850467289, 0.6448598130841121, 0.6542056074766355, 0.6542056074766355, 0.6728971962616822, 0.6635514018691588, 0.6822429906542056]

In [ ]:
max_score = max(scores)
scores_ind = [i for i, v in enumerate(scores) if v == max_score]
scores_ind

[1]

In [ ]:
knn = KNeighborsClassifier(2)

# обучаем
knn.fit(X_train, y_train)

# предсказываем значения
y_pred = knn.predict(X_test)

print(accuracy_score(y_test,y_pred))

0.8130841121495327

In [ ]:
#метод ближайших соседей с масштабированием


# создаем модель
# как подобрать лучшее число соседей?
scores = []
for i in range(1,20):

    knn = KNeighborsClassifier(i)
    # log = LogisticRegression()
    knn.fit(X_train,y_train)
    answers = knn.predict(X_test) # метод predict возвращыет вектор ответов для X_test
    
    scores.append(knn.score(X_test,y_test))
    # accuracy_score(y_test,answers)

print(scores)

[0.7476635514018691, 0.8130841121495327, 0.7570093457943925, 0.7850467289719626, 0.7476635514018691, 0.719626168224299, 0.7009345794392523, 0.7009345794392523, 0.7009345794392523, 0.7009345794392523, 0.6728971962616822, 0.6635514018691588, 0.6915887850467289, 0.6448598130841121, 0.6542056074766355, 0.6542056074766355, 0.6728971962616822, 0.6635514018691588, 0.6822429906542056]

In [ ]:
max_score = max(scores)
scores_ind = [i for i, v in enumerate(scores) if v == max_score]
scores_ind

[1]

In [ ]:
knn = KNeighborsClassifier(1)

# обучаем
knn.fit(X_train, y_train)

# предсказываем значения
y_pred = knn.predict(X_test)

print(accuracy_score(y_test,y_pred))

0.7476635514018691